import React,{useEffect,useState} from "react";
import {FaBox,FaMapMarkerAlt,FaTruck} from "react-icons/fa";
import {toast} from "react-toastify";
import {AccountShell} from "./AccountShell";
export default function OrderDetailsPage(){
 const id=window.location.pathname.split("/").filter(Boolean).pop(),[o,setO]=useState(null);
 useEffect(()=>{fetch(`${import.meta.env.VITE_BACKEND_URL}/api/orders/${id}`,{headers:{Authorization:`Bearer ${localStorage.getItem("token")}`}}).then(r=>r.json()).then(d=>setO(d.order||d.data||d)).catch(e=>toast.error(e.message))},[id]);
 if(!o)return <AccountShell title="Order details"><div className="ok-card ok-empty">Loading order...</div></AccountShell>;
 return <AccountShell title="Order details"><div style={{marginTop:20}}><div className="ok-card" style={{padding:18}}><div className="ok-row"><div className="ok-grow"><b>Order #{o.orderNumber||o._id?.slice(-8)?.toUpperCase()}</b><div className="ok-small">{new Date(o.createdAt||Date.now()).toLocaleString()}</div></div><span className="ok-chip success">{o.status||"Processing"}</span></div></div><section className="ok-section"><div className="ok-label">Items</div><div className="ok-card ok-list">{(o.items||[]).map((x,i)=><div className="ok-list-item" key={x._id||i}><img className="ok-avatar" style={{width:58,height:58,borderRadius:12}} src={x.image||x.product?.image||"https://via.placeholder.com/100"} alt=""/><div className="ok-grow"><b>{x.name||x.product?.name||"Product"}</b><div className="ok-small">Qty {x.quantity||1}</div></div><b>₹{Number(x.price||0).toLocaleString("en-IN")}</b></div>)}</div></section><section className="ok-section"><div className="ok-label">Delivery address</div><div className="ok-card" style={{padding:18}}><div className="ok-row"><div className="ok-circle"><FaMapMarkerAlt/></div><div className="ok-grow"><b>{o.shippingAddress?.fullName||o.address?.fullName||"Delivery address"}</b><p className="ok-muted">{Object.values(o.shippingAddress||o.address||{}).filter(v=>typeof v==="string").join(", ")}</p></div></div></div></section><section className="ok-section"><div className="ok-label">Order summary</div><div className="ok-card" style={{padding:18}}><Line t="Subtotal" v={o.subtotal}/><Line t="Shipping" v={o.shippingCost}/><Line t="Discount" v={o.discount} minus/><hr/><Line t="Total" v={o.totalAmount??o.total} bold/></div></section><button className="ok-btn ok-primary ok-full" style={{marginTop:18}} onClick={()=>window.location.href=`/account/orders/${id}/track`}><FaTruck/> Track order</button></div></AccountShell>
}
function Line({t,v,bold,minus}){return <div className="ok-row" style={{padding:"5px 0",fontWeight:bold?800:500}}><span className="ok-grow">{t}</span><span>{minus?"-":""}₹{Number(v||0).toLocaleString("en-IN")}</span></div>}
